name: Build Project with Platform

on:
  workflow_dispatch:

jobs:
  build:
    name: Build with Demo Platform
    uses: asharma54-wiq/Demo-Platform-Repo/.github/workflows/checkout-calling-repo.yaml@v3.0
    secrets: inherit
